baseURL = 'https://ranjhith.com/'
languageCode = 'en-us'
title = "Ranjhith Kalisamy's website"
theme = 'archie'
copyright = "© Ranjhith Kalisamy"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourDisqusShortname"

pagination.pagerSize=3 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ranjhith"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/ranrwx/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'
